spring:
   datasource:
      username: medical_theme
      password: Password1!
      url: jdbc:mysql://localhost:3306/personal_medical
      # initialization-mode: never
   
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true # Set this to true to defer datasource initialization
      
   
   sql:
      init:
         mode: never
   
   
   logging:
     level:
       org.springframework.boot: DEBUG
 